<script src="{{asset('assets/admin/plugins/global/plugins.bundle.js')}}"></script>
<script src="{{asset('assets/admin/js/scripts.bundle.js')}}"></script>
<script src="{{asset("assets/admin/plugins/custom/datatables/datatables.bundle.js")}}"></script>
<script src="{{ asset('assets/admin/js/utils/constants.js') }}" defer></script>
<script src="{{asset("assets/admin/plugins/custom/formrepeater/formrepeater.bundle.js")}}"></script>
{{--<script src="{{asset("assets/admin/plugins/custom/formrepeater/formrepeater.bundle.js")}}"></script>--}}
{{--<script src="{{asset('assets/admin/js/custom/widgets.js')}}"></script>
<script src="{{asset('assets/admin/js/custom/apps/chat/chat.js')}}"></script>
<script src="{{asset('assets/admin/js/custom/modals/create-app.js')}}"></script>
<script src="{{asset('assets/admin/js/custom/modals/upgrade-plan.js')}}"></script>
<script src="{{asset('assets/admin/js/custom/modals/upgrade-plan.js')}}"></script>
<script src="{{asset('assets/admin/js/custom/intro.js')}}"></script>
<script src="{{asset("assets/admin/plugins/custom/fullcalendar/fullcalendar.bundle.js")}}"></script>
<script src="{{asset("assets/admin/plugins/custom/vis-timeline/vis-timeline.bundle.js")}}"></script>
<script src="{{asset("assets/admin/js/widgets.bundle.js")}}"></script>
<script src="{{asset("assets/admin/js/custom/utilities/modals/upgrade-plan.js")}}"></script>
<script src="{{asset("assets/admin/js/custom/utilities/modals/users-search.js")}}"></script>
<script src="{{asset("assets/admin/js/custom/utilities/modals/create-app.js")}}"></script>--}}
{{--<script src="{{asset("assets/admin/js/custom/apps/calendar/calendar.js")}}"></script>--}}
@yield('js')
